apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: aap-automation-hub
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  image_pull_policy: IfNotPresent
  object_storage_s3_secret: aap-s3-secret-km6748kg96
  web:
    replicas: 1
  content:
    log_level: INFO
    replicas: 2
  api:
    log_level: INFO
    replicas: 1
  loadbalancer_protocol: http
  resource_manager:
    replicas: 1
  storage_type: S3
  worker:
    replicas: 2