apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management-observability
resources:
- ./rbac/cluster-role-binding.yaml
- ./rbac/cluster-role.yaml
- ./rbac/sa.yaml
- grafana-dev-job.yaml
- post-sync-job.yaml
