apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  labels:
    operators.coreos.com/advanced-cluster-management.open-cluster-management: ''
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  availabilityConfig: High
  imagePullSecret: multiclusterhub-operator-pull-secret
