---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging 
spec:
  channel: "stable-5.3" 
  installPlanApproval: Manual
  startingCSV: cluster-logging.5.3.2-20
