apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-mgmt-config

generatorOptions:
  disableNameSuffixHash: true

resources:
- authrealm.yaml.secret

secretGenerator:
- name: github-oauth-clientsecret
  envs:
    - github-clientsecret.secret