apiVersion: v1
kind: Service
metadata:
  name: automation-controller-service
  labels:
    app.kubernetes.io/name: automation-controller
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: metrics
  selector:
    app.kubernetes.io/name: automation-controller
