apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- velero.yaml

#patches:
#  - path: patch.yaml
#    target:
#     kind: Velero
#     group: oadp.openshift.io
#     version: v1alpha1
#    name: velero
#      namespace: openshift-adp
