---
collections:
  - name: community.general
  - name: community.crypto
    version: 1.8.0
  - name: containers.podman
  - name: azure.azcollection
    version: 1.12.0
  - name: awx.awx
    version: 19.4.0

