apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

bases:
- ../../base
patches:
- velero.yaml

secretGenerator:
- name: cloud-credentials-azure
  namespace: openshift-adp
  files:
  - cloud=storage.secret
