apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml

secretGenerator:
- name: github-group-sync
  namespace: group-sync-operator
  envs:
    - github.secret
