apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- catalogsource.yaml
- operatorgroup.yaml
- subscription.yaml
- idpconfig.yaml
- managedclusterset.yaml
- placement.yaml
- authrealm.yaml.secret

secretGenerator:
- name: github-oauth-clientsecret
  files:
    - github-clientsecret.secret
